import { Problem } from './index'

export const problem002: Problem = {
  problemDetails: {
    problemNumber: 2,
    title: `Even Fibonacci numbers`,
    description: `Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.`
  },
  run: () => {
    let sum = 0
    let curr = 0
    let prev1 = 1
    let prev2 = 0
    while (curr <= 4000000) {
      curr = prev1 + prev2
      prev2 = prev1
      prev1 = curr
      if (curr % 2 === 0) {
        sum += curr
      }
    }

    return sum
  }
}
